//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migracion_inicial
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSIT_Solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSIT_Solicitudes()
        {
            this.Encomienda = new HashSet<Encomienda>();
        }
    
        public int id_solicitud { get; set; }
        public int id_tipotramite { get; set; }
        public int id_tipoexpediente { get; set; }
        public int id_subtipoexpediente { get; set; }
        public Nullable<int> MatriculaEscribano { get; set; }
        public string NroExpediente { get; set; }
        public int id_estado { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUser { get; set; }
        public string NroExpedienteSade { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> FechaLibrado { get; set; }
        public string CodigoSeguridad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomienda> Encomienda { get; set; }
    }
}
