//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationAGIP.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DGHP_SolicitudesEntities : DbContext
    {
        public DGHP_SolicitudesEntities()
            : base("name=DGHP_SolicitudesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
    
        public virtual int SSIT_Solicitudes_Historial_LibradoUso_INSERT(Nullable<int> id_solicitud, Nullable<System.DateTime> fechaLibrado, Nullable<System.DateTime> createDate, Nullable<System.Guid> createUser)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            var fechaLibradoParameter = fechaLibrado.HasValue ?
                new ObjectParameter("fechaLibrado", fechaLibrado) :
                new ObjectParameter("fechaLibrado", typeof(System.DateTime));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("createDate", createDate) :
                new ObjectParameter("createDate", typeof(System.DateTime));
    
            var createUserParameter = createUser.HasValue ?
                new ObjectParameter("createUser", createUser) :
                new ObjectParameter("createUser", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SSIT_Solicitudes_Historial_LibradoUso_INSERT", id_solicitudParameter, fechaLibradoParameter, createDateParameter, createUserParameter);
        }
    }
}
