//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationAGIP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int id_param { get; set; }
        public string cod_param { get; set; }
        public string nom_param { get; set; }
        public string valorchar_param { get; set; }
        public Nullable<decimal> valornum_param { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
