//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DGHP_SolicitudesEntities : DbContext
    {
        public DGHP_SolicitudesEntities()
            : base("name=DGHP_SolicitudesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAFYCO_Menues> BAFYCO_Menues { get; set; }
        public DbSet<BAFYCO_Parametros> BAFYCO_Parametros { get; set; }
        public DbSet<BAFYCO_Perfiles> BAFYCO_Perfiles { get; set; }
        public DbSet<BAFYCO_Rel_Usuarios_Perfiles> BAFYCO_Rel_Usuarios_Perfiles { get; set; }
    }
}
