//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_Encomiendas_Titulares
    {
        public int id_rel_encomienda_empresa { get; set; }
        public int id_encomienda { get; set; }
        public int id_empresa { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
