//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Roles
    {
        public aspnet_Roles()
        {
            this.ConsejoProfesional_RolesPermitidos = new HashSet<ConsejoProfesional_RolesPermitidos>();
            this.GrupoConsejos_Roles_Clasificacion = new HashSet<GrupoConsejos_Roles_Clasificacion>();
            this.aspnet_Users = new HashSet<aspnet_Users>();
            this.Profesional_Perfiles_Inhibiciones = new HashSet<Profesional_Perfiles_Inhibiciones>();
            this.Encomienda_URLxROL = new HashSet<Encomienda_URLxROL>();
            this.Rel_UsuariosProf_Roles_Clasificacion = new HashSet<Rel_UsuariosProf_Roles_Clasificacion>();
            this.Cursos = new HashSet<Cursos>();
            this.aspnet_Users1 = new HashSet<aspnet_Users>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string LoweredRoleName { get; set; }
        public string Description { get; set; }
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual ICollection<ConsejoProfesional_RolesPermitidos> ConsejoProfesional_RolesPermitidos { get; set; }
        public virtual ICollection<GrupoConsejos_Roles_Clasificacion> GrupoConsejos_Roles_Clasificacion { get; set; }
        public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
        public virtual ICollection<Profesional_Perfiles_Inhibiciones> Profesional_Perfiles_Inhibiciones { get; set; }
        public virtual ICollection<Encomienda_URLxROL> Encomienda_URLxROL { get; set; }
        public virtual ICollection<Rel_UsuariosProf_Roles_Clasificacion> Rel_UsuariosProf_Roles_Clasificacion { get; set; }
        public virtual ICollection<Cursos> Cursos { get; set; }
        public virtual ICollection<aspnet_Users> aspnet_Users1 { get; set; }
    }
}
