//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASR_TiposDeElevadores
    {
        public ASR_TiposDeElevadores()
        {
            this.ASR_Ubicaciones_Elevadores = new HashSet<ASR_Ubicaciones_Elevadores>();
        }
    
        public int id_tipoelevador { get; set; }
        public string nom_tipoelevador { get; set; }
    
        public virtual ICollection<ASR_Ubicaciones_Elevadores> ASR_Ubicaciones_Elevadores { get; set; }
    }
}
