//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVH_visitas
    {
        public int id_visita_avh { get; set; }
        public string SessionId_avh { get; set; }
        public System.DateTime fecha_visita_avh { get; set; }
        public string Navegadores_avh { get; set; }
        public string ipclient_avh { get; set; }
    }
}
