//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupEscribanos
    {
        public int Matricula { get; set; }
        public Nullable<int> Registro { get; set; }
        public string ApyNom { get; set; }
        public Nullable<int> Cargo { get; set; }
        public string Calle { get; set; }
        public string NroPuerta { get; set; }
        public string Piso { get; set; }
        public string Depto { get; set; }
        public Nullable<int> CodPostal { get; set; }
        public string Localidad { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Inhibido { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
