//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAA_Estados
    {
        public int id_estado { get; set; }
        public string cod_estado { get; set; }
        public string nom_estado_usuario { get; set; }
        public string nom_estado_interno { get; set; }
        public int orden { get; set; }
        public bool visible_Aprob_prof { get; set; }
    }
}
