//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAA_TiposDeCertificados
    {
        public int id_tipocertificado { get; set; }
        public string codigo_tipocertificado { get; set; }
        public string nombre_tipocertificado { get; set; }
        public string descripcion_tipocertificado { get; set; }
        public int id_ImactoAmbiental { get; set; }
        public int puntaje_para_peligrosos { get; set; }
        public int prioridad { get; set; }
    }
}
