//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAA_TiposDeCertificados
    {
        public int id_tipocertificado { get; set; }
        public string codigo_tipocertificado { get; set; }
        public string nombre_tipocertificado { get; set; }
        public string descripcion_tipocertificado { get; set; }
        public int id_ImactoAmbiental { get; set; }
        public int puntaje_para_peligrosos { get; set; }
        public int prioridad { get; set; }
        public string AcronimoSADE { get; set; }
        public string NombreArchivoCertificado { get; set; }
    }
}
