//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigo_urbanistico
    {
        public int id { get; set; }
        public string s { get; set; }
        public string m { get; set; }
        public string p { get; set; }
        public Nullable<int> mixtura1 { get; set; }
        public Nullable<int> mixtura2 { get; set; }
        public Nullable<int> mixtura3 { get; set; }
        public string dist_1_grp { get; set; }
        public string dist_1_esp { get; set; }
        public string dist_2_grp { get; set; }
        public string dist_2_esp { get; set; }
        public string dist_3_grp { get; set; }
        public string dist_3_esp { get; set; }
        public string dist_4_grp { get; set; }
        public string dist_4_esp { get; set; }
        public string aph_zona_1 { get; set; }
        public string aph_subzona_1 { get; set; }
        public string aph_zona_2 { get; set; }
        public string aph_subzona_2 { get; set; }
        public string aph_zona_3 { get; set; }
        public string aph_subzona_3 { get; set; }
        public string U_Zonas_1 { get; set; }
        public string U_Zonas_2 { get; set; }
        public string U_Zonas_3 { get; set; }
        public string U_Zonas_4 { get; set; }
        public string U_Zonas_5 { get; set; }
        public string U_Zonas_6 { get; set; }
        public string U_Zonas_7 { get; set; }
        public string U_Zonas_8 { get; set; }
        public string U_Zonas_9 { get; set; }
    }
}
