//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comisarias
    {
        public Comisarias()
        {
            this.Ubicaciones = new HashSet<Ubicaciones>();
            this.Ubicaciones_Historial_Cambios = new HashSet<Ubicaciones_Historial_Cambios>();
        }
    
        public int id_comisaria { get; set; }
        public string nom_comisaria { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<Ubicaciones> Ubicaciones { get; set; }
        public virtual ICollection<Ubicaciones_Historial_Cambios> Ubicaciones_Historial_Cambios { get; set; }
    }
}
