//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsejoProfesional
    {
        public ConsejoProfesional()
        {
            this.EncomiendaExt = new HashSet<EncomiendaExt>();
            this.Profesional = new HashSet<Profesional>();
            this.Profesional_historial = new HashSet<Profesional_historial>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Profesion { get; set; }
        public string Calle { get; set; }
        public string NroPuerta { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> id_consejo_habilitaciones { get; set; }
        public int id_grupoconsejo { get; set; }
    
        public virtual GrupoConsejos GrupoConsejos { get; set; }
        public virtual ICollection<EncomiendaExt> EncomiendaExt { get; set; }
        public virtual ICollection<Profesional> Profesional { get; set; }
        public virtual ICollection<Profesional_historial> Profesional_historial { get; set; }
    }
}
