//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGFYCO_Ubicaciones
    {
        public DGFYCO_Ubicaciones()
        {
            this.ASR_Ubicaciones_Elevadores = new HashSet<ASR_Ubicaciones_Elevadores>();
            this.DGFYCO_Ubicaciones_DatosAdicionales = new HashSet<DGFYCO_Ubicaciones_DatosAdicionales>();
            this.DGFYCO_Ubicaciones_Puertas = new HashSet<DGFYCO_Ubicaciones_Puertas>();
        }
    
        public int id_dgubicacion { get; set; }
        public System.Guid userid_consorcio { get; set; }
        public int id_ubicacion { get; set; }
        public Nullable<int> id_subtipoubicacion { get; set; }
        public string local_subtipoubicacion { get; set; }
        public bool Dado_baja { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> CreateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUser { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
        public virtual aspnet_Users aspnet_Users2 { get; set; }
        public virtual ICollection<ASR_Ubicaciones_Elevadores> ASR_Ubicaciones_Elevadores { get; set; }
        public virtual ICollection<DGFYCO_Ubicaciones_DatosAdicionales> DGFYCO_Ubicaciones_DatosAdicionales { get; set; }
        public virtual ICollection<DGFYCO_Ubicaciones_Puertas> DGFYCO_Ubicaciones_Puertas { get; set; }
        public virtual SubTiposDeUbicacion SubTiposDeUbicacion { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
