//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistritosEscolares
    {
        public DistritosEscolares()
        {
            this.Ubicaciones = new HashSet<Ubicaciones>();
        }
    
        public int id_distritoescolar { get; set; }
        public string nom_distritoescolar { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<Ubicaciones> Ubicaciones { get; set; }
    }
}
