//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.SolicitudDocumento = new HashSet<SolicitudDocumento>();
        }
    
        public int Id { get; set; }
        public int IdTipoVerificacion { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public bool Requerido { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoVerificacion TipoVerificacion { get; set; }
        public virtual ICollection<SolicitudDocumento> SolicitudDocumento { get; set; }
    }
}
