//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emails_Perfil_Relacion_Config
    {
        public int id_rel { get; set; }
        public int id_profile { get; set; }
        public string ws_username { get; set; }
    
        public virtual Emails_Perfil_Config Emails_Perfil_Config { get; set; }
    }
}
