//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emails_Tipos
    {
        public Emails_Tipos()
        {
            this.Emails = new HashSet<Emails>();
        }
    
        public int id_tipo_email { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Emails> Emails { get; set; }
    }
}
