//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncomiendaExt_Ubicaciones
    {
        public EncomiendaExt_Ubicaciones()
        {
            this.EncomiendaExt_Ubicaciones_PropiedadHorizontal = new HashSet<EncomiendaExt_Ubicaciones_PropiedadHorizontal>();
            this.EncomiendaExt_Ubicaciones_Puertas = new HashSet<EncomiendaExt_Ubicaciones_Puertas>();
        }
    
        public int id_encomiendaubicacion { get; set; }
        public int id_encomienda { get; set; }
        public int id_ubicacion { get; set; }
        public Nullable<int> id_subtipoubicacion { get; set; }
        public string local_subtipoubicacion { get; set; }
        public string deptoLocal_encomiendaubicacion { get; set; }
        public int id_zonaplaneamiento { get; set; }
    
        public virtual EncomiendaExt_Ubicaciones EncomiendaExt_Ubicaciones1 { get; set; }
        public virtual EncomiendaExt_Ubicaciones EncomiendaExt_Ubicaciones2 { get; set; }
        public virtual EncomiendaExt_Ubicaciones EncomiendaExt_Ubicaciones11 { get; set; }
        public virtual EncomiendaExt_Ubicaciones EncomiendaExt_Ubicaciones3 { get; set; }
        public virtual ICollection<EncomiendaExt_Ubicaciones_PropiedadHorizontal> EncomiendaExt_Ubicaciones_PropiedadHorizontal { get; set; }
        public virtual ICollection<EncomiendaExt_Ubicaciones_Puertas> EncomiendaExt_Ubicaciones_Puertas { get; set; }
        public virtual SubTiposDeUbicacion SubTiposDeUbicacion { get; set; }
        public virtual Zonas_Planeamiento Zonas_Planeamiento { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        public virtual EncomiendaExt EncomiendaExt { get; set; }
    }
}
