//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncomiendaExt_Estados
    {
        public EncomiendaExt_Estados()
        {
            this.EncomiendaExt_TransicionEstados = new HashSet<EncomiendaExt_TransicionEstados>();
            this.EncomiendaExt_TransicionEstados1 = new HashSet<EncomiendaExt_TransicionEstados>();
            this.EncomiendaExt = new HashSet<EncomiendaExt>();
        }
    
        public int id_estado { get; set; }
        public string cod_estado { get; set; }
        public string nom_estado { get; set; }
        public string nom_estado_consejo { get; set; }
    
        public virtual ICollection<EncomiendaExt_TransicionEstados> EncomiendaExt_TransicionEstados { get; set; }
        public virtual ICollection<EncomiendaExt_TransicionEstados> EncomiendaExt_TransicionEstados1 { get; set; }
        public virtual ICollection<EncomiendaExt> EncomiendaExt { get; set; }
    }
}
