//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomienda_URLxROL
    {
        public int Id { get; set; }
        public System.Guid RoleId { get; set; }
        public string url { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
    }
}
