//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncomiendaExt_Empresas
    {
        public int id_encomiendaext_empresa { get; set; }
        public int id_encomienda { get; set; }
        public string TipoEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string Cuit { get; set; }
        public string Calle { get; set; }
        public Nullable<int> NroPuerta { get; set; }
        public string Piso { get; set; }
        public string Depto { get; set; }
        public string Localidad { get; set; }
        public string CodigoPostal { get; set; }
    
        public virtual EncomiendaExt EncomiendaExt { get; set; }
    }
}
