//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomienda_Tipos_Destinos
    {
        public Encomienda_Tipos_Destinos()
        {
            this.Encomienda_Rel_TiposDestinos_TiposUsos = new HashSet<Encomienda_Rel_TiposDestinos_TiposUsos>();
            this.Encomienda_Rel_TiposSobrecargas_TiposDestinos = new HashSet<Encomienda_Rel_TiposSobrecargas_TiposDestinos>();
            this.Encomienda_Sobrecarga_Detalle1 = new HashSet<Encomienda_Sobrecarga_Detalle1>();
        }
    
        public int id_tipo_destino { get; set; }
        public string descripcion { get; set; }
        public bool requiere_detalle_2 { get; set; }
    
        public virtual ICollection<Encomienda_Rel_TiposDestinos_TiposUsos> Encomienda_Rel_TiposDestinos_TiposUsos { get; set; }
        public virtual ICollection<Encomienda_Rel_TiposSobrecargas_TiposDestinos> Encomienda_Rel_TiposSobrecargas_TiposDestinos { get; set; }
        public virtual ICollection<Encomienda_Sobrecarga_Detalle1> Encomienda_Sobrecarga_Detalle1 { get; set; }
    }
}
