//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomienda_Estados
    {
        public Encomienda_Estados()
        {
            this.Encomienda_TransicionEstados = new HashSet<Encomienda_TransicionEstados>();
            this.Encomienda_TransicionEstados1 = new HashSet<Encomienda_TransicionEstados>();
            this.Encomienda = new HashSet<Encomienda>();
        }
    
        public int id_estado { get; set; }
        public string cod_estado { get; set; }
        public string nom_estado { get; set; }
        public string nom_estado_consejo { get; set; }
    
        public virtual ICollection<Encomienda_TransicionEstados> Encomienda_TransicionEstados { get; set; }
        public virtual ICollection<Encomienda_TransicionEstados> Encomienda_TransicionEstados1 { get; set; }
        public virtual ICollection<Encomienda> Encomienda { get; set; }
    }
}
