//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENG_Config_BandejaAsignacion
    {
        public int id_bandejaAsig { get; set; }
        public int id_tarea { get; set; }
        public Nullable<int> id_perfil_asignador { get; set; }
        public Nullable<int> id_perfil_asignado { get; set; }
    
        public virtual ENG_Tareas ENG_Tareas { get; set; }
        public virtual SGI_Perfiles SGI_Perfiles { get; set; }
        public virtual SGI_Perfiles SGI_Perfiles1 { get; set; }
    }
}
