//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio_Mail_Log_Errores
    {
        public int ID_SQL { get; set; }
        public int ID_Mail { get; set; }
        public System.DateTime Fecha { get; set; }
        public string LogError { get; set; }
    }
}
