//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio_Mail_Prioridades
    {
        public int ID_Prioridad { get; set; }
        public System.TimeSpan Hora_Desde { get; set; }
        public System.TimeSpan Hora_Hasta { get; set; }
        public int Tiempo_Reenvio { get; set; }
        public string Obervacion { get; set; }
        public Nullable<System.DateTime> Ultima_Ejecucion { get; set; }
    }
}
