//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio_Mail_Log_Errores
    {
        public int ID_SQL { get; set; }
        public int ID_Mail { get; set; }
        public System.DateTime Fecha { get; set; }
        public string LogError { get; set; }
    }
}
