//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichas
    {
        public Fichas()
        {
            this.Rubros = new HashSet<Rubros>();
        }
    
        public int id_ficha { get; set; }
        public string nom_ficha { get; set; }
        public string archivo_ficha { get; set; }
        public int supmin_ficha { get; set; }
        public int supmax_ficha { get; set; }
    
        public virtual ICollection<Rubros> Rubros { get; set; }
    }
}
