//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InicioTramite_Menues
    {
        public InicioTramite_Menues()
        {
            this.InicioTramite_Menues1 = new HashSet<InicioTramite_Menues>();
            this.InicioTramite_Perfiles = new HashSet<InicioTramite_Perfiles>();
        }
    
        public int Id_menu { get; set; }
        public string Descripcion_menu { get; set; }
        public string Aclaracion_menu { get; set; }
        public string Pagina_menu { get; set; }
        public string IconCssClass_menu { get; set; }
        public Nullable<int> Id_menu_padre { get; set; }
        public int NroOrden { get; set; }
        public bool Visible { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
    
        public virtual ICollection<InicioTramite_Menues> InicioTramite_Menues1 { get; set; }
        public virtual InicioTramite_Menues InicioTramite_Menues2 { get; set; }
        public virtual ICollection<InicioTramite_Perfiles> InicioTramite_Perfiles { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
    }
}
