//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ley257_Solicitudes
    {
        public Ley257_Solicitudes()
        {
            this.Ley257_Solicitudes_HistorialEstados = new HashSet<Ley257_Solicitudes_HistorialEstados>();
            this.Ley257_Solicitudes_Pagos = new HashSet<Ley257_Solicitudes_Pagos>();
        }
    
        public int id_solicitud { get; set; }
        public int id_encomienda { get; set; }
        public int id_dgubicacion { get; set; }
        public string observaciones_ubicacion { get; set; }
        public int id_profesional { get; set; }
        public int id_estado { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUser { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
        public virtual Ley257_Estados Ley257_Estados { get; set; }
        public virtual ICollection<Ley257_Solicitudes_HistorialEstados> Ley257_Solicitudes_HistorialEstados { get; set; }
        public virtual ICollection<Ley257_Solicitudes_Pagos> Ley257_Solicitudes_Pagos { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
