//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Tad_Token
    {
        public int login_tad_token_id { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public string tokenJWT { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual Login_Tad_Token Login_Tad_Token1 { get; set; }
        public virtual Login_Tad_Token Login_Tad_Token2 { get; set; }
    }
}
