//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_TiposDeDocumentosRequeridos_TipoNormativa
    {
        public int id_tdoc_tnor { get; set; }
        public int id_tdocreq { get; set; }
        public int id_tnor { get; set; }
    
        public virtual TipoNormativa TipoNormativa { get; set; }
        public virtual TiposDeDocumentosRequeridos TiposDeDocumentosRequeridos { get; set; }
    }
}
