//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_TipoTramite_TiposDeDocumentosRequeridos
    {
        public int id_rel_tiptra_tdocreq { get; set; }
        public int id_tipotramite { get; set; }
        public int id_tdocreq { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual TipoTramite TipoTramite { get; set; }
        public virtual TiposDeDocumentosRequeridos TiposDeDocumentosRequeridos { get; set; }
    }
}
