//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_Rubros_Solicitudes_Nuevas
    {
        public int id_relrubSol { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int id_Solicitud { get; set; }
        public decimal Superficie { get; set; }
    
        public virtual SSIT_Solicitudes_Nuevas SSIT_Solicitudes_Nuevas { get; set; }
    }
}
