//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubrosFormulasCN
    {
        public int IdFormula { get; set; }
        public string Codigo { get; set; }
        public string Formula { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
