//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubrosCondiciones
    {
        public RubrosCondiciones()
        {
            this.RubrosZonasCondiciones = new HashSet<RubrosZonasCondiciones>();
        }
    
        public int id_condicion { get; set; }
        public string cod_condicion { get; set; }
        public string nom_condicion { get; set; }
        public int SupMin_condicion { get; set; }
        public int SupMax_condicion { get; set; }
    
        public virtual ICollection<RubrosZonasCondiciones> RubrosZonasCondiciones { get; set; }
    }
}
