//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubrosZonasCondiciones
    {
        public string cod_rubro { get; set; }
        public string cod_ZonaHab { get; set; }
        public string cod_condicion { get; set; }
    
        public virtual RubrosCondiciones RubrosCondiciones { get; set; }
        public virtual Zonas_Habilitaciones Zonas_Habilitaciones { get; set; }
    }
}
