//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTipoActividad
    {
        public int idTipoActividad { get; set; }
        public int idSolicitud { get; set; }
        public string nroDisposicion { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
    }
}
