//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPuerta
    {
        public SolicitudPuerta()
        {
            this.TipoSector = new HashSet<TipoSector>();
        }
    
        public int Id { get; set; }
        public int IdSolicitudPartida { get; set; }
        public int CodCalle { get; set; }
        public int NroPuerta { get; set; }
        public string Observaciones { get; set; }
    
        public virtual SolicitudPartida SolicitudPartida { get; set; }
        public virtual ICollection<TipoSector> TipoSector { get; set; }
    }
}
