//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDeUbicacion
    {
        public TiposDeUbicacion()
        {
            this.SubTiposDeUbicacion = new HashSet<SubTiposDeUbicacion>();
        }
    
        public int id_tipoubicacion { get; set; }
        public string descripcion_tipoubicacion { get; set; }
        public Nullable<bool> RequiereSMP { get; set; }
    
        public virtual ICollection<SubTiposDeUbicacion> SubTiposDeUbicacion { get; set; }
    }
}
