//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitularInhibido
    {
        public int TitularInhibidoId { get; set; }
        public int TipoDocumentoPersonalId { get; set; }
        public int NroDocumento { get; set; }
        public int TipoInhibicionId { get; set; }
        public string Detalle { get; set; }
    
        public virtual TipoDocumentoPersonal TipoDocumentoPersonal { get; set; }
        public virtual TipoInhibicion TipoInhibicion { get; set; }
    }
}
