//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransicionEstadoSolicitud
    {
        public int Id { get; set; }
        public int IdEstadoActual { get; set; }
        public int IdEstadoSiguiente { get; set; }
        public string Rol { get; set; }
    
        public virtual TipoEstadoSolicitud TipoEstadoSolicitud { get; set; }
        public virtual TipoEstadoSolicitud TipoEstadoSolicitud1 { get; set; }
    }
}
