//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transf_Plantas
    {
        public Transf_Plantas()
        {
            this.Transf_ConformacionLocal = new HashSet<Transf_ConformacionLocal>();
        }
    
        public int id_transftiposector { get; set; }
        public int id_solicitud { get; set; }
        public int id_tiposector { get; set; }
        public string detalle_transftiposector { get; set; }
    
        public virtual TipoSector TipoSector { get; set; }
        public virtual ICollection<Transf_ConformacionLocal> Transf_ConformacionLocal { get; set; }
        public virtual Transf_Solicitudes Transf_Solicitudes { get; set; }
    }
}
