//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_Puertas_temp
    {
        public int id_ubic_puerta_temp { get; set; }
        public int id_ubicacion_temp { get; set; }
        public string tipo_puerta { get; set; }
        public int codigo_calle { get; set; }
        public int NroPuerta_ubic { get; set; }
    
        public virtual Ubicaciones_temp Ubicaciones_temp { get; set; }
    }
}
