//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_ZonasComplementarias_Historial_Cambios
    {
        public int id_ubic_zonas_histcam { get; set; }
        public int id_ubihistcam { get; set; }
        public int id_ubicacion { get; set; }
        public string tipo_ubicacion { get; set; }
        public int id_zonaplaneamiento { get; set; }
    
        public virtual Ubicaciones_Historial_Cambios Ubicaciones_Historial_Cambios { get; set; }
        public virtual Zonas_Planeamiento Zonas_Planeamiento { get; set; }
    }
}
