//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_Historial_Cambios_UsuariosIntervinientes
    {
        public int id_ubihistcamusu { get; set; }
        public int id_ubihistcam { get; set; }
        public Nullable<System.Guid> Userid { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
