//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_DireccionesConformadas
    {
        public int id_direccion { get; set; }
        public int id_ubicacion { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
