//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_Operaciones_Detalle
    {
        public int id_operacion_det { get; set; }
        public int id_operacion { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public Nullable<int> id_ubicacion_temp { get; set; }
        public string Detalle { get; set; }
    
        public virtual Ubicaciones_Operaciones Ubicaciones_Operaciones { get; set; }
    }
}
