//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_Distritos_Excepciones_RubrosCN
    {
        public int IdExcepcionRubro { get; set; }
        public int IdDistrito { get; set; }
        public Nullable<int> IdZona { get; set; }
        public Nullable<int> idSubZona { get; set; }
        public int IdRubro { get; set; }
        public decimal DesdeM2 { get; set; }
        public decimal HastaM2 { get; set; }
        public bool SobreAvenida { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public bool Denegado { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Ubicaciones_CatalogoDistritos Ubicaciones_CatalogoDistritos { get; set; }
        public virtual Ubicaciones_CatalogoDistritos_Subzonas Ubicaciones_CatalogoDistritos_Subzonas { get; set; }
        public virtual Ubicaciones_CatalogoDistritos_Zonas Ubicaciones_CatalogoDistritos_Zonas { get; set; }
        public virtual RubrosCN RubrosCN { get; set; }
    }
}
