//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_Operaciones_Detalle
    {
        public int id_operacion_det { get; set; }
        public int id_operacion { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public Nullable<int> id_ubicacion_temp { get; set; }
        public string Detalle { get; set; }
    
        public virtual Ubicaciones_Operaciones Ubicaciones_Operaciones { get; set; }
    }
}
