//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones_DireccionesConformadas
    {
        public int id_direccion { get; set; }
        public int id_ubicacion { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
