//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsDatosCallejeroUSIG
    {
        public int Codigo { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public Nullable<int> Altura_inicio { get; set; }
        public Nullable<int> Altura_fin { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}
