//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsEscribanos_InstrumentoPrivado
    {
        public int id_inspriv { get; set; }
        public int id_derecho_ocupacion { get; set; }
        public Nullable<System.DateTime> fecha_certificacion_inspriv { get; set; }
        public Nullable<int> nro_acta_inspriv { get; set; }
        public Nullable<int> nro_matricula_escribano_inspriv { get; set; }
        public string registro_inspriv { get; set; }
        public string jurisdiccion_inspriv { get; set; }
        public Nullable<System.DateTime> fecha_pago_impsellos_inspriv { get; set; }
        public string banco_pago_inspriv { get; set; }
        public Nullable<decimal> monto_pago_inspriv { get; set; }
    
        public virtual wsEscribanos_DerechoOcupacion wsEscribanos_DerechoOcupacion { get; set; }
    }
}
