//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsEscribanos_Files_TRANSF
    {
        public int id_docadj_file { get; set; }
        public int id_docadjunto { get; set; }
        public int id_escribano_file { get; set; }
    
        public virtual Transf_DocumentosAdjuntos Transf_DocumentosAdjuntos { get; set; }
        public virtual wsEscribanos_Files wsEscribanos_Files { get; set; }
    }
}
