//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsEscribanos_Tipos_Escrituras
    {
        public wsEscribanos_Tipos_Escrituras()
        {
            this.wsEscribanos_ActaNotarial = new HashSet<wsEscribanos_ActaNotarial>();
        }
    
        public int id_tipo_escritura { get; set; }
        public string desc_tipo_escritura { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<wsEscribanos_ActaNotarial> wsEscribanos_ActaNotarial { get; set; }
    }
}
