//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsEscribanos_PersonasJuridicas
    {
        public wsEscribanos_PersonasJuridicas()
        {
            this.wsEscribanos_PersonasJuridicas_Representantes = new HashSet<wsEscribanos_PersonasJuridicas_Representantes>();
        }
    
        public int id_wsPersonaJuridica { get; set; }
        public int id_actanotarial { get; set; }
        public Nullable<int> id_personajuridica { get; set; }
        public Nullable<decimal> porcentaje_titularidad { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_pago_IIBB { get; set; }
        public string direccion_sede_social { get; set; }
        public Nullable<System.DateTime> fecha_contrato_social { get; set; }
        public Nullable<int> instrumento_constitucion { get; set; }
        public Nullable<int> nro_escritura_constitucion { get; set; }
        public Nullable<int> nro_matricula_escribano_constitucion { get; set; }
        public string registro_constitucion { get; set; }
        public string jurisdiccion_constitucion { get; set; }
        public string nom_organismo_inscripcion { get; set; }
        public Nullable<System.DateTime> fecha_incripcion { get; set; }
        public string datos_incripcion { get; set; }
        public string nom_tipo_IVA { get; set; }
        public Nullable<int> exento_IB { get; set; }
        public Nullable<int> reciente_insc_IB { get; set; }
        public Nullable<int> acredita_insc_IB { get; set; }
        public Nullable<int> acredita_pago_IB { get; set; }
        public Nullable<int> acredita_pago_aportes_IB { get; set; }
    
        public virtual ICollection<wsEscribanos_PersonasJuridicas_Representantes> wsEscribanos_PersonasJuridicas_Representantes { get; set; }
        public virtual wsEscribanos_ActaNotarial wsEscribanos_ActaNotarial { get; set; }
    }
}
