//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsPagos_Procesados
    {
        public int id_pago_BU { get; set; }
        public int EstadoPago_BU { get; set; }
        public int EstadoPago_Nuevo { get; set; }
        public string Job { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
