//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsPagos_BoletaUnica_HistorialEstados3
    {
        public int id_hist { get; set; }
        public int id_pago_BU { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> ActualizadoFecha { get; set; }
    
        public virtual wsPagos_BoletaUnica wsPagos_BoletaUnica { get; set; }
    }
}
