//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsPagos_BatchLog
    {
        public int id_batch { get; set; }
        public int id_pago { get; set; }
        public string ErrorMessage_batch { get; set; }
        public int EstadoPago_batch { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual wsPagos wsPagos { get; set; }
    }
}
