//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class wsPagos_Procesados_PagadosSinFecha
    {
        public int id_pago_BU { get; set; }
        public System.DateTime FechaAnterior { get; set; }
        public System.DateTime FechaPagado { get; set; }
        public string job { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
